export class Palabras {
    palabrasJuego = [
        "hola",
        "inefable",
        "super",
        "etereo",
        "sempiterno",
        "petricor",
        "perenne",
        "luminiscencia",
        "mondo",
        "infinito",
        "ademan",
        "epoca",
        "bonhomia",
        "soledad",
        "resiliencia",
        "melancolia", 
        "melifluo",
        "elocuencia",
        "efervescencia",
        "ataraxia",
        "olvido", 
        "ascendrado",
        "arrebol",
        "sonambulo",
        "serendipia",
        "alba",
        "epifania",
        "incandescencia",
        "nostalgia",
        "inmarcesible",
        "aurora",
        "desenlace",
        "messi"
        
    ];  
}